platform :ios, '9.0'
use_frameworks!

workspace 'Timmee.xcworkspace'

target 'Timmee' do
  project 'Timmee.xcodeproj'
    
  pod 'SwipeCellKit'
  pod 'Foto'
  
  pod 'Fabric'
  pod 'Crashlytics'
end

target 'UIComponents' do
    project 'UIComponents.xcodeproj'
end

target 'TasksKit' do
  project 'TasksKit.xcodeproj'  
end

target 'Workset' do
  project 'Workset.xcodeproj'
  
  pod 'SwipeCellKit'
  pod 'Foto'
end
